In [7]:
from importlib import reload
import pathlib
import os
import sys
import pickle
from pprint import pprint
import numba

In [2]:
this_path = pathlib.Path('.').parent.absolute()
src_path = os.path.join(this_path, '..')
sys.path.insert(0, src_path)

In [3]:
import dnashapeparams as dsp
import find_motifs as fm
import numpy as np
import inout

In [4]:
from matplotlib import pyplot as plt
%matplotlib inline

In [8]:
params = [
    "test/BRCA1_input/BRCA1_30_bp_height_train_4.fa.EP",
    "test/BRCA1_input/BRCA1_30_bp_height_train_4.fa.HelT",
    "test/BRCA1_input/BRCA1_30_bp_height_train_4.fa.MGW",
    "test/BRCA1_input/BRCA1_30_bp_height_train_4.fa.ProT",
    "test/BRCA1_input/BRCA1_30_bp_height_train_4.fa.Roll",
]
param_names = [
    "EP",
    "HelT",
    "MGW",
    "ProT",
    "Roll",
]
this_dist = inout.constrained_manhattan_distance
search_method = "brute"
in_file = "test/BRCA1_input/BRCA1_30_bp_height_train_4.txt"
kmer = 15
ignorestart = 2
ignoreend = 2
threshold_perc = 0.05
thresh_sd_from_mean = 2.0
threshold_seeds = 2.0
threshold_match = 2.0
seeds_per_seq_thresh = 1
seeds_per_seq = 2
num_seeds = 5000
rc = False
numprocs = 6

In [9]:
numba.set_num_threads(numprocs)

In [34]:
shape_fname_dict = {n:fn for n,fn in zip(param_names, params)}
rec_db = inout.RecordDatabase(in_file, shape_fname_dict)
rec_db.determine_center_spread()
rec_db.normalize_shape_values()
rec_db.compute_windows(wsize=15)
rec_db.initialize_weights()
rec_db.set_initial_thresholds(
    dist = this_dist,
    threshold_sd_from_mean = thresh_sd_from_mean
)

In [11]:
with open('fwd_rev_initial_mutual_information.pkl','rb') as f:
    d = pickle.load(f)
    rec_db.mi = d['mi']
    rec_db.hits = d['hits']

In [13]:
rec_db.hits.shape

(1764, 41, 1764, 2)

In [30]:
fm = reload(fm)
inout = reload(inout)

In [31]:
cmi_windows = fm.aic_motifs2(rec_db)

151
1764
2.844401143674271
-9733.047234882828
Candidate 1 AIC: -9444.768610654333
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [0. 6.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [6. 6.]
 [6. 7.]
 [7. 7.]
 [7. 8.]]
1.0673227534215832
-3463.514674071346
Candidate 2 AIC: -9241.007123854639
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  8.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 9. 11.]
 [10. 10.]]
1.8379224143005046
-6182.19027765218
[[ 0.  0.]
 [ 0.  1.]
 [ 0

1.472461031234919
-4892.842518196794
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 0. 11.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 11.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 14.]
 [ 8. 19.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 15.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 15.]
 [12. 12.]
 [12. 13.]
 [13. 13.]
 [13. 15.]
 [13. 

2.7079464845628167
-9251.635197537618
Candidate 8 AIC: -8826.454455661216
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]]
1.62588725963623
-5434.130251996619
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 11.

2.068879219456084
-6997.005886241064
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 16.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 13.]
 [12. 14.]
 [13. 17.]
 [14. 15.]
 [14. 18.]
 [14. 21.]
 [15. 15.]
 [16. 19.]
 [17. 19.]]
1.719697693434446
-5765.0934624367255
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]


3.5242468702165097
-12131.542958123846
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 13.]]
4.865668707966242
-16864.079201704903
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.

1.6906996102087208
-5662.788224816367
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 11.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 12.]]
3.3690802364091814
-11584.115074051591
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.

[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [2. 8.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 9.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]]
5.038089366775931
-17472.379285985484
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [2. 8.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 9.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]]
3.5713795363755017
-12297.82700433277
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 6.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [2. 8.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4.

2.239147813204801
-7597.713484986537
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 14.]
 [11. 13.]
 [11. 15.]
 [16. 18.]]
2.2099869971115593
-7494.834125809582
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]


5.187158499217056
-17998.295185237774
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 14.]
 [11. 13.]
 [11. 15.]
 [16. 18.]]
4.391678056937872
-15191.840184876812
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]

3.477915364738118
-11968.085406796079
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 12.]
 [10. 11.]
 [11. 11.]
 [12. 12.]
 [12. 13.]
 [12. 14.]]
2.7995419262979926
-9574.783915979318
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]

1.7454966654368358
-5856.112235661157
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]]
4.109338921648662
-14195.747715576481
Candidate 19 AIC: -8514.174611958671
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6. 

4.770736331951571
-16529.157779125144
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  8.]
 [ 7.  7.]
 [ 8.  9.]
 [ 9. 10.]]
2.3293189712206717
-7915.837330466529
Working on candidate index: 20
Candidate 20 AIC: -8509.568166053126
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  9.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 13.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7

1.769935984103977
-5942.334151918831
Candidate 21 AIC: -8481.746265731039
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 14.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 15.]
 [10. 18.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 17.]
 [12. 14.]
 [12. 15.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [

2.4354367854835637
-8290.220979186013
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 14.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 15.]
 [10. 18.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 17.]
 [12. 14.]
 [12. 15.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [14. 14.]
 [15. 17.]
 [16.

2.6312196998599338
-8980.943101105846
Candidate 22 AIC: -8476.291590233548
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 11.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  9.]
 [ 8. 11.]
 [ 8. 14.]
 [ 9. 10.]
 [ 9. 11.]
 [10. 10.]
 [10. 11.]]
1.4164044755230272
-4695.07498964524
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  

3.1749565621302063
-10899.246751195367
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 11.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  9.]
 [ 8. 11.]
 [ 8. 14.]
 [ 9. 10.]
 [ 9. 11.]
 [10. 10.]
 [10. 11.]]
1.5294888761084982
-5094.036754910781
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.

[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  8.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 15.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 5. 11.]
 [ 5. 12.]
 [ 5. 13.]
 [ 5. 14.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 13.]
 [ 6. 15.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]
 [10. 10.]
 [10. 13.]
 [10. 17.]
 [11. 11.]
 [12. 14.]
 [13. 16.]
 [14. 14.]
 [15. 17.]]
2.773302380541358
-9482.210798549911
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  8.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.

3.568367277140388
-12287.199753751289
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  8.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 15.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 5. 11.]
 [ 5. 12.]
 [ 5. 13.]
 [ 5. 14.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 13.]
 [ 6. 15.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]
 [10. 10.]
 [10. 13.]
 [10. 17.]
 [11. 11.]
 [12. 14.]
 [13. 16.]
 [14. 14.]
 [15. 17.]]
2.255534978860904
-7655.527405421269
Candidate 24 AIC: -8421.783435847297
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  

2.7814034207243137
-9510.791268315379
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [11. 11.]
 [11. 13.]
 [11. 15.]
 [12. 12.]
 [12. 13.]
 [13. 15.]
 [13. 16.]
 [13. 17.]
 [14. 18.]
 [15. 20.]
 [17. 18.]
 [18. 19.]
 [18. 20.]
 [19. 19.]]
2.817976820885999
-9639.822224085805
[[ 0.  0.]
 [ 0.  1.]


2.095520416669361
-7090.996030009505
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 12.]
 [11. 13.]
 [12. 13.]
 [13. 15.]]
2.0899080415331768
-7071.1955705290475
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]

1.3728182406948068
-4541.302753171279
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 15.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 12.]
 [11. 13.]
 [12. 13.]
 [13. 15.]]
3.2971337759196504
-11330.287961444526
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.

5.923467593795832
-20595.993670911696
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 15.]
 [11. 12.]
 [11. 14.]
 [12. 12.]
 [12. 13.]
 [12. 14.]
 [14. 16.]]
3.7288210567743567
-12853.28068829993
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]

2.2164011833271924
-7517.463374778335
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 15.]
 [11. 12.]
 [11. 14.]
 [12. 12.]
 [12. 13.]
 [12. 14.]
 [14. 16.]]
2.7450920911220478
-9382.684897478584
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]

2.886520677312562
-9881.644949558719
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 14.]
 [ 9. 10.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [11. 12.]]
4.075756193534851
-14077.267850790955
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]


5.029544944057998
-17442.234562636615
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 14.]
 [ 9. 10.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [11. 12.]]
1.1606646941033043
-3792.8250407964574
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.

3.5281771024788364
-12145.408817545334
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 8.  9.]]
1.3995790880473697
-4635.7150226311205
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6

4.132445944288453
-14277.269291449664
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9.  9.]
 [10. 10.]
 [11. 13.]]
5.839569399920784
-20300.000842920526
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]

4.238230907444662
-14650.478641464768
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9.  9.]
 [10. 10.]
 [11. 13.]]
3.3484536913500937
-11511.34462308313
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]

2.5563637478230143
-8716.851302319594
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 12.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8. 10.]
 [ 8. 14.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 11.]
 [10. 10.]
 [10. 11.]
 [10. 14.]
 [11. 13.]
 [12. 18.]
 [13. 13.]]
2.229909788127739
-7565.121732514664
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]


2.6041700368687413
-8885.51189007292
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 12.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8. 10.]
 [ 8. 14.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 11.]
 [10. 10.]
 [10. 11.]
 [10. 14.]
 [11. 13.]
 [12. 18.]
 [13. 13.]]
2.8682062434182636
-9817.031626779633
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]


2.853611332172076
-9765.540779903084
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  9.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8. 10.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 14.]
 [10. 12.]]
1.629134956977397
-5445.588128216256
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 

3.5001513918866083
-12046.534110575954
Candidate 32 AIC: -8326.998475491328
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 16.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 15.]
 [14. 16.]
 [15. 16.]
 [15. 17.]
 [16. 16.]]
1.1316744219807413
-3690.5473607480553
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0

3.063270076574167
-10505.216830153662
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 16.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 15.]
 [14. 16.]
 [15. 16.]
 [15. 17.]
 [16. 16.]]
3.140271443179133
-10776.877651535982
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]

1.4393419509886007
-4775.998403087783
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  7.]
 [ 1.  8.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 16.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 15.]
 [14. 16.]
 [15. 16.]
 [15. 17.]
 [16. 16.]]
1.741240172759788
-5841.095329496532
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]


3.8223021378337654
-13183.081942277524
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]]
3.2886339447885535
-11300.300557214017
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9

3.0486099998464145
-10453.49607945815
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]]
2.3917764785912805
-8136.187416470038
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]

4.6138890162585575
-15975.800449360191
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 4. 11.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 5. 13.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9. 10.]
 [ 9. 12.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [12. 13.]
 [13. 14.]]
2.9234912977520917
-10012.07729846938
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.

[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 4. 11.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 5. 13.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9. 10.]
 [ 9. 12.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [12. 13.]
 [13. 14.]]
2.8088012164712146
-9607.450691710445
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3

2.3260303799851325
-7904.235180587548
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 4. 11.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 5. 13.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9. 10.]
 [ 9. 12.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [12. 13.]
 [13. 14.]]
2.63838031168064
-9006.205739609299
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 

2.313950618146396
-7861.617780820485
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  9.]
 [ 1. 13.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 5. 12.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 16.]
 [ 9. 19.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 17.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 

3.587962085675372
-12356.330238262712
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  9.]
 [ 1. 13.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 5. 12.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 16.]
 [ 9. 19.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 17.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11.

2.312819144843528
-7857.625943007967
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 1.  9.]
 [ 1. 13.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 4. 14.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 5. 12.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 8. 15.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [ 9. 16.]
 [ 9. 19.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [10. 14.]
 [10. 17.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 

2.974035149533893
-10190.396007555575
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9. 10.]
 [10. 10.]]
4.075776645285892
-14077.340004568627
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]

3.9900622259363216
-13774.939533103343
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9. 10.]
 [10. 10.]]
2.883087706969435
-9869.533430188167
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]

3.6054692142347617
-12418.09538782024
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [11. 12.]
 [12. 14.]
 [12. 15.]
 [13. 15.]
 [14. 14.]
 [15. 17.]]
3.8541037081544465
-13295.277882368888
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.

3.0941987454974655
-10614.333174115058
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [11. 12.]
 [12. 14.]
 [12. 15.]
 [13. 15.]
 [14. 14.]
 [15. 17.]]
5.6543684263494285
-19646.611808160782
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5

6.6073004037701155
-23008.555824500967
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 12.]
 [ 9. 15.]
 [10. 10.]
 [10. 11.]
 [11. 12.]
 [12. 14.]
 [12. 15.]
 [13. 15.]
 [14. 14.]
 [15. 17.]]
2.9034381277959533
-9941.329714864123
Candidate 38 AIC: -8230.011958281199
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3

2.355273365201942
-8007.404432432451
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [6. 6.]
 [6. 8.]]
4.19095811677426
-14483.700235979588
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [6. 6.]
 [6. 8.]]
3.779249918782763
-13031.193713465587
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 7.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [6. 6.]
 [6. 8.]]
4.080566439276287
-14

3.948815802153733
-13629.42214999837
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 14.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [14. 14.]
 [14. 15.]
 [16. 16.]
 [16. 17.]
 [18. 18.]]
4.59627118029039
-15913.644724064497
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 

2.650624467545985
-9049.403121502235
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 14.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [14. 14.]
 [14. 15.]
 [16. 16.]
 [16. 17.]
 [18. 18.]]
5.294478657846518
-18376.920704882516
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]


3.641034341287542
-12543.56915606245
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 14.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [12. 12.]
 [12. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [14. 14.]
 [14. 15.]
 [16. 16.]
 [16. 17.]
 [18. 18.]]
3.0398970275765818
-10422.75671329018
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]


4.031846457748923
-13922.3543029382
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [12. 13.]
 [13. 15.]]
6.666842988244762
-23218.62206252752
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [

6.2925661443814995
-21898.17335737793
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [12. 13.]
 [13. 15.]]
3.1145067999763
-10685.979990316386
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 

1.7852931248396051
-5996.514144434127
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [12. 13.]
 [13. 15.]]
3.0852849579179304
-10582.885331534459
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.

3.101089470339683
-10638.643651358403
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [14. 20.]]
2.6181262848084943
-8934.749532804368
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]

3.1572289311555553
-10836.7036691168
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [14. 20.]]
4.845748564737225
-16793.80093639293
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 

5.9456747075803555
-20674.340368343495
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 12.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 12.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [14. 20.]]
2.2986564532700036
-7807.659967136573
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.

3.3301386599215586
-11446.729192203258
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 9. 10.]
 [10. 10.]
 [10. 12.]]
3.604213055379085
-12413.663659377411
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.

2.5138433244104466
-8566.839248520055
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 8.  8.]
 [ 8.  9.]
 [ 9. 10.]
 [10. 10.]
 [10. 12.]]
2.9336916885728552
-10048.064277285033
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.

1.1776528015497358
-3852.759083867468
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 9. 10.]
 [10. 10.]]
2.0840628073945173
-7050.573584487857
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]

2.3905390498279684
-8131.821767793073
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 9. 10.]
 [10. 10.]]
1.8425126227488668
-6198.3845330580025
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.

3.243516938895483
-11141.127760423265
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 9. 10.]
 [10. 10.]]
2.32912133125753
-7915.140056676566
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  9.]
 [ 2. 10.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 12.]
 [ 5.  5.]
 [ 5.  6.]
 

1.6823812524912871
-5633.441058789261
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2. 11.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [11. 13.]
 [11. 16.]
 [12. 19.]
 [13. 18.]
 [14. 15.]
 [14. 16.]
 [16. 20.]]
2.2085879019402963
-7489.898118045366
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]

3.0630515273675902
-10504.445788552859
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2. 11.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [11. 13.]
 [11. 16.]
 [12. 19.]
 [13. 18.]
 [14. 15.]
 [14. 16.]
 [16. 20.]]
1.9204079399793972
-6473.199212247313
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.

2.4240945026922796
-8250.205405498362
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2. 11.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [10. 11.]
 [10. 13.]
 [11. 11.]
 [11. 13.]
 [11. 16.]
 [12. 19.]
 [13. 18.]
 [14. 15.]
 [14. 16.]
 [16. 20.]]
2.548977169531774
-8690.791454108097
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]


4.212757785002447
-14560.609465488633
Candidate 45 AIC: -8153.061902352907
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [11. 11.]]
1.1892611754356115
-3893.713426936837
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5. 

4.801677494203016
-16638.31819954824
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [11. 11.]]
3.198980524945652
-10984.00329200826
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 

1.8121352634770458
-6091.213209547018
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 8.  8.]
 [ 8.  9.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [10. 10.]
 [11. 11.]]
1.4930472260871475
-4965.470613635456
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]

3.187240830283539
-10942.585649240325
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9. 10.]
 [11. 12.]]
3.4258345614114214
-11784.344332659495
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.

2.9550416126945347
-10123.386809586318
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 7.  7.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 9. 10.]
 [11. 12.]]
2.9871627952867277
-10236.710341771575
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 3. 10.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7

1.0727608647238565
-3482.7003307457658
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 8.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]
 [6. 8.]
 [6. 9.]
 [8. 8.]]
2.071779159838985
-7007.236875911939
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 8.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]
 [6. 8.]
 [6. 9.]
 [8. 8.]]
2.290816425372331
-7780.000348713585
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3

3.71027178443637
-12787.838855491515
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 8.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]
 [6. 8.]
 [6. 9.]
 [8. 8.]]
3.6123472284614633
-12442.361022012043
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 [3. 8.]
 [4. 4.]
 [4. 5.]
 [4. 6.]
 [4. 7.]
 [4. 8.]
 [5. 5.]
 [5. 6.]
 [5. 7.]
 [5. 8.]
 [5. 9.]
 [6. 6.]
 [6. 7.]
 [6. 8.]
 [6. 9.]
 [8. 8.]]
3.5176251316385274
-12108.181464420724
[[0. 0.]
 [0. 1.]
 [0. 2.]
 [0. 3.]
 [0. 4.]
 [0. 5.]
 [1. 1.]
 [1. 2.]
 [1. 3.]
 [1. 4.]
 [1. 5.]
 [1. 7.]
 [2. 2.]
 [2. 3.]
 [2. 4.]
 [2. 5.]
 [2. 6.]
 [2. 7.]
 [3. 3.]
 [3. 4.]
 [3. 5.]
 [3. 6.]
 

3.8907391919585983
-13424.527869229934
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 14.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 16.]
 [12. 12.]
 [12. 13.]
 [13. 16.]
 [14. 16.]
 [15. 16.]
 [18. 18.]]
5.985857450681745
-20816.105086005195
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.

2.202919515037185
-7469.900049051189
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 14.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 16.]
 [12. 12.]
 [12. 13.]
 [13. 16.]
 [14. 16.]
 [15. 16.]
 [18. 18.]]
2.685472533954359
-9172.347099790977
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 

3.990465891768494
-13776.363666159246
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  8.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 12.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 14.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [10. 10.]
 [10. 11.]
 [10. 12.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 16.]
 [12. 12.]
 [12. 13.]
 [13. 16.]
 [14. 16.]
 [15. 16.]
 [18. 18.]]
7.2888241638971385
-25412.971650229105
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.

1.460813433725725
-4851.749794184358
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 16.]
 [12. 12.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [13. 21.]
 [14. 14.]
 [14. 19.]
 [15. 16.]
 [16. 

2.7799559625584234
-9505.684635906118
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 16.]
 [12. 12.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [13. 21.]
 [14. 14.]
 [14. 19.]
 [15. 16.]
 [16.

2.86253300470879
-9797.01644061261
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 16.]
 [12. 12.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [13. 21.]
 [14. 14.]
 [14. 19.]
 [15. 16.]
 [16. 17

2.5706200800750394
-8767.147642504739
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 16.]
 [12. 12.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [13. 21.]
 [14. 14.]
 [14. 19.]
 [15. 16.]
 [16.

[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 2.  7.]
 [ 2.  8.]
 [ 2.  9.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 4. 11.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 12.]
 [ 7. 13.]
 [ 7. 14.]
 [ 8.  8.]
 [ 8.  9.]
 [ 8. 10.]
 [ 8. 11.]
 [ 8. 12.]
 [ 8. 13.]
 [ 9.  9.]
 [ 9. 10.]
 [ 9. 11.]
 [ 9. 12.]
 [ 9. 13.]
 [ 9. 14.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 11.]
 [11. 12.]
 [11. 13.]
 [11. 14.]
 [11. 16.]
 [12. 12.]
 [13. 13.]
 [13. 14.]
 [13. 15.]
 [13. 16.]
 [13. 21.]
 [14. 14.]
 [14. 19.]
 [15. 16.]
 [16. 17.]
 [16. 19.]
 [17. 22.]
 [18. 19.]

1.043158047375146
-3378.261591139515
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 13.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8. 11.]]
2.9893633013323075
-10244.473727100381
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 13.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8. 11.]]
4.621707315243016
-16003.383408177362
[[ 0.  0.]
 [ 0.  1.]
 [ 0

3.486751598371519
-11999.259639054719
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 13.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8. 11.]]
3.3040010088604452
-11354.515559259651
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 0.  7.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  6.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4. 13.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 7.  8.]
 [ 7.  9.]
 [ 8. 11.]]
3.5903855158158575
-12364.880099798345
[[ 0.  0.]
 [ 0.  1.]
 [

1.2556638950433632
-4127.982221712985
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 9. 10.]
 [ 9. 13.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 13.]
 [11. 14.]
 [12. 14.]
 [13. 15.]]
2.017056772195034
-6814.17629230408
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 

1.3744420473325112
-4547.0315429891
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 9. 10.]
 [ 9. 13.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 13.]
 [11. 14.]
 [12. 14.]
 [13. 15.]]
2.615984628678285
-8927.19376997699
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 

2.591153843769073
-8839.59076081729
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 9. 10.]
 [ 9. 13.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 13.]
 [11. 14.]
 [12. 14.]
 [13. 15.]]
2.151011511250391
-7286.768611691379
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [

1.7530509909163294
-5882.76389595281
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]
 [ 3.  3.]
 [ 3.  4.]
 [ 3.  5.]
 [ 3.  6.]
 [ 3.  7.]
 [ 3.  8.]
 [ 3.  9.]
 [ 4.  4.]
 [ 4.  5.]
 [ 4.  6.]
 [ 4.  7.]
 [ 4.  8.]
 [ 4.  9.]
 [ 4. 10.]
 [ 5.  5.]
 [ 5.  6.]
 [ 5.  7.]
 [ 5.  8.]
 [ 5.  9.]
 [ 5. 10.]
 [ 5. 11.]
 [ 6.  6.]
 [ 6.  7.]
 [ 6.  8.]
 [ 6.  9.]
 [ 6. 10.]
 [ 6. 11.]
 [ 6. 12.]
 [ 6. 13.]
 [ 7.  7.]
 [ 7.  8.]
 [ 7.  9.]
 [ 7. 10.]
 [ 7. 11.]
 [ 7. 13.]
 [ 8.  8.]
 [ 8. 10.]
 [ 9. 10.]
 [ 9. 13.]
 [10. 10.]
 [10. 12.]
 [10. 13.]
 [11. 13.]
 [11. 14.]
 [12. 14.]
 [13. 15.]]
3.430330865951029
-11800.207295075232
[[ 0.  0.]
 [ 0.  1.]
 [ 0.  2.]
 [ 0.  3.]
 [ 0.  4.]
 [ 0.  5.]
 [ 0.  6.]
 [ 1.  1.]
 [ 1.  2.]
 [ 1.  3.]
 [ 1.  4.]
 [ 1.  5.]
 [ 1.  6.]
 [ 1.  7.]
 [ 2.  2.]
 [ 2.  3.]
 [ 2.  4.]
 [ 2.  5.]
 [ 2.  6.]


In [33]:
len(cmi_windows)

52